[package]
name = "proto-build"
version = "0.1.0"
edition = "2021"
publish = false
rust-version = "1.57"

[dependencies]
prost = "0.9"
prost-build = "0.9"
regex = "1"
tonic = "0.6"
tonic-build = "0.6"
walkdir = "2"
