[workspace]
resolver = "2"
members = [
    "proto-build",
    "proto",
    "common",
    "bindings/wasm",
    "bindings/cpp",
    "wallet-connect"
]

[profile.release]
opt-level = "s"
debug = true
lto = "thin"
