[package]
name = "defi-wallet-core-cpp"
version = "0.2.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
defi-wallet-core-common = { path = "../../common" , features=["login"]}
defi-wallet-core-proto = { version = "0.1", path = "../../proto" }
cxx = "1"
anyhow = "1"
serde="1"
serde_json="1"
siwe = { version = "0.2" }
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "0a031417d8ec9e8696229eb5d172f7155ec3c79c" }
hex = "0.4"
tokio = { version = "1", features = ["rt"] }

[build-dependencies]
cxx-build = "1"


[lib]
crate-type = ["staticlib", "cdylib"]
