[package]
name = "defi-wallet-core-cpp"
version = "0.1.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
defi-wallet-core-common = { path = "../../common" , features=["login"]}
defi-wallet-core-proto = { version = "0.1", path = "../../proto" }
cxx = "1"
anyhow = "1"
serde="1"
serde_json="1"
siwe = { version = "0.2" }
tokio = { version="1", features=["full"] }
hex = "0.4"
ethers = { git = "https://github.com/gakonst/ethers-rs", rev = "de275db56a1be948cf4a543e1837f5add6f4750c" }



[build-dependencies]
cxx-build = "1"


[lib]
crate-type = ["staticlib", "cdylib"]
