[package]
name = "defi-wallet-core-cpp"
version = "0.1.0"
edition = "2021"

[dependencies]
defi-wallet-core-common = { path = "../../common" }
defi-wallet-core-proto = { version = "0.1", path = "../../proto" }
cxx = "1"
anyhow = "1"
serde_json="1"

[build-dependencies]
cxx-build = "1"


[lib]
crate-type = ["staticlib"]
