[package]
name = "defi-wallet-core-common"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
eyre = "0.6"
cosmrs = "0.3"
defi-wallet-core-proto = { version = "0.1", default-features = false, path = "../defi-wallet-core-proto" }
prost = "0.9"
rand_core = { version = "0.6", features = ["std"] }
secrecy = "0.8"
thiserror = "1"
uniffi = "^0.15"
uniffi_macros = "^0.15"

[build-dependencies]
uniffi_build = { version = "^0.15", features=["builtin-bindgen"] }
