[package]
name = "defi-wallet-core-common"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
eyre = "0.6"
cosmrs = "0.4"
defi-wallet-core-proto = { version = "0.1", default-features = false, path = "../proto" }
prost = "0.9"
rand_core = { version = "0.6", features = ["std"] }
reqwest = { version = "0.11", features = ["blocking", "json"], default-features = false }
secrecy = "0.8"
serde = "1"
serde_json = "1"
serde_with = "1"
tendermint-rpc = "0.23"
thiserror = "1"
uniffi = "^0.15"
uniffi_macros = "^0.15"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cosmos-sdk-proto = { version = "0.9", features = ["grpc"] }
tokio = { version = "1", features = ["rt"] }
tonic = { version = "0.6", features = ["tls", "tls-roots"] }

[build-dependencies]
uniffi_build = { version = "^0.15", features=["builtin-bindgen"] }
