[package]
name = "defi-wallet-core-common"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[features]
default = []
login = ["siwe"]

[dependencies]
anyhow = "1"
bip39 = "1"
cfg-if = "1.0.0"
eyre = "0.6"
cosmrs = "0.4"
defi-wallet-core-proto = { version = "0.1", default-features = false, path = "../proto" }
# NOTE: add `features = ["legacy"]` if non-EIP-1559 network support is required
ethers = { version = "0.6" }
prost = "0.9"
# NOTE: crate `bip39` cannot work with latest crate `rand` (0.8.0)
# FIXME: https://github.com/rust-bitcoin/rust-bip39/issues/14
rand = "0.6"
rand_core = { version = "0.6", features = ["std"] }
reqwest = { version = "0.11", features = ["blocking", "json"] }
secrecy = "0.8"
serde = "1"
serde_json = "1"
serde_with = "1"
siwe = { version = "0.1", optional = true }
tendermint-rpc = "0.23"
thiserror = "1"
uniffi = "^0.15"
uniffi_macros = "^0.15"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
cosmos-sdk-proto = { version = "0.9", features = ["grpc"] }
tokio = { version = "1", features = ["rt"] }
tonic = { version = "0.6", features = ["tls", "tls-roots"] }

[build-dependencies]
uniffi_build = { version = "^0.15", features=["builtin-bindgen"] }
