name: Android Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: cargo install uniffi_bindgen
      - run: |
          echo 'export NDK_HOME=$ANDROID_NDK_ROOT' >> $BASH_ENV
          echo 'export JAVA_HOME=$JAVA_HOME_17_X64' >> $BASH_ENV
      - run: |
          make android

          