name: Android Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: cargo install uniffi_bindgen
      - run: |
          export NDK_HOME=$ANDROID_NDK_ROOT
          export JAVA_HOME=$JAVA_HOME_11_X64
          make android
