name: Android Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          export JAVA_HOME=$JAVA_HOME_8_X64
          $ANDROID_SDK_ROOT/tools/bin/sdkmanager --list
          echo y | $ANDROID_SDK_ROOT/tools/bin/sdkmanager "system-images;android-30;google_apis;x86_64"
          echo no | $ANDROID_SDK_ROOT/tools/bin/avdmanager create avd -n testavd -k "system-images;android-30;google_apis;x86_64"
          $ANDROID_SDK_ROOT/tools/emulator @testavd &
      - name: NDK cache
        uses: actions/cache@v2
        with:
          path: |
            NDK/
          key: ${{ runner.os }}-ndk-${{ hashFiles('android_build.sh') }}
          restore-keys: |
            ${{ runner.os }}-ndk-
      - name: Android module cache
        uses: actions/cache@v2
        with:
          path: |
            mobile_modules/android_module/
          key: ${{ runner.os }}-android-${{ hashFiles('**/Cargo.lock', 'android_build.sh') }}
          restore-keys: |
            ${{ runner.os }}-android-
      - name: Rust cache
        uses: Swatinem/rust-cache@v1
      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: command -v uniffi-bindgen || cargo install uniffi_bindgen --version 0.17.0
      - run: |
          export NDK_HOME=$ANDROID_NDK_ROOT
          export JAVA_HOME=$JAVA_HOME_11_X64
          make android
