name: Android Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Android cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            target/
            NDK/
            mobile_modules/android_module/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-android-${{ hashFiles('android_build.sh') }}
      - run: cargo install uniffi_bindgen
      - run: |
          export NDK_HOME=$ANDROID_NDK_ROOT
          export JAVA_HOME=$JAVA_HOME_11_X64
          make android
