name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          make -v
          pwd
          ls
          cat Makefile
          cat ios_build.sh
          make ios

          
