name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  merge_group:
  pull_request:
    paths-ignore:
      - README.md

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v1
      - name: Check with clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Check with clippy for defi-wallet-core-cpp
        run: cargo clippy -p defi-wallet-core-cpp --all-features -- -D warnings
      - name: Check with clippy for defi-wallet-core-wasm
        run: cargo clippy -p defi-wallet-core-wasm --target wasm32-unknown-unknown --all-features -- -D warnings
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: Swatinem/rust-cache@v1
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage
        run: cargo llvm-cov --all-features --lcov --output-path lcov.info
      - name: Generate code coverage for defi-wallet-core-cpp
        run: cargo llvm-cov --all-features -p defi-wallet-core-cpp --lcov --output-path lcov-cpp.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info,./lcov-cpp.info
          fail_ci_if_error: true

  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: cargo fmt --all -- --check
