name: Documents
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - release/**
    tags:
      - "*"

jobs:
  cpp_documents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
           # pin to nix-2.13 to workaround compability issue of 2.14,
           # see: https://github.com/cachix/install-nix-action/issues/161
           install_url: https://releases.nixos.org/nix/nix-2.13.3/install
      - uses: cachix/cachix-action@v10
        with:
          name: cronos
          extraPullNames: dapp
          # github don't pass secrets for pull request from fork repos,
          # in that case the push is disabled naturally.
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: 'Tar debug files'
        if: failure()
        run: tar cfz debug_files.tar.gz -C /tmp/pytest-of-runner .
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug-files
          path: debug_files.tar.gz
          if-no-files-found: ignore
      - name: Generate doxygen
        run: make cpp-docs-doxygen
      - name: Generate sphinx
        run: make cpp-docs-sphinx
      - name: Generate gitbook
        run: make cpp-docs-gitbook
      - name: Generate mdbook
        run: make cpp-docs-mdbook
