name: IOS Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: cargo install uniffi_bindgen
      - run: |
          make ios

          