name: IOS Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ios-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: iOS cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/git/db/
            target/
            mobile_modules/ios_module/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-ios-${{ hashFiles('ios_build.sh') }}
      - run: cargo install uniffi_bindgen
      - run: |
          make ios
