name: Run Lint
# Lint runs golangci-lint over the entire cronos repository This workflow is
# run on every pull request and push to main The `golangci` will pass without
# running if no *.{go, mod, sum} files have been changed.
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
jobs:
  lint-python:
    name: Lint python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: cronos
      - run: nix-shell -I nixpkgs=./nix -p test-env --run "make lint-py"

  lint-nix:
    name: Lint nix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
      - run: nix-shell -I nixpkgs=./nix -p nixpkgs-fmt --run "make lint-nix"
