name: Mac Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags:
      - "v*.*.*"
  merge_group:
  pull_request:
    paths-ignore:
      - README.md

jobs:
  mac-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3

      - name: Compile Cpp
        run: make build_cpp
