name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android-build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          export JAVA_HOME=$JAVA_HOME_11_X64
          $ANDROID_SDK_ROOT/tools/android create avd -n testdev -k "system-images;android-30;default;x86_64"
          $ANDROID_SDK_ROOT/tools/emulator @testdev &
          