name: integration tests
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
      - release/**
    tags:
      - "*"

jobs:
  integration_tests:
    runs-on: ubuntu-latest
    env:
      WASM_BINDGEN_TEST_TIMEOUT: 60
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
          name: cronos
          extraPullNames: dapp
          # github don't pass secrets for pull request from fork repos,
          # in that case the push is disabled naturally.
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - name: 'Tar debug files'
        if: failure()
        run: tar cfz debug_files.tar.gz -C /tmp/pytest-of-runner .
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug-files
          path: debug_files.tar.gz
          if-no-files-found: ignore
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Run wasm tests
        run: make wasm-ci-tests
      - name: Run cpp tests
        run: make cpp-ci-tests
