name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ci:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          brew install binutils
          export PATH=/usr/local/opt/binutils/bin:$PATH
          readelf -v

