name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ci:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: |
          command -v uniffi-bindgen || cargo install uniffi_bindgen
          uniffi-bindgen generate common/src/common.udl --config-path common/uniffi.toml --language kotlin --out-dir bindings/android
          cat bindings/android/com/defi/wallet/core/common/common.kt
